POST http://localhost:8080/register
Content-Type: application/json

{
  "username": "riki123",
  "email": "riki@example.com",
  "password": "12345678"
}

### 
# @name loginAdmin
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "riki@example.com",
  "password": "12345678"
}

###
// 添加商品
@token = {{loginAdmin.response.body.$.token}}
POST http://localhost:8080/products
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "iPhone 15",
    "description": "苹果新款",
    "price": 9999,
    "stock": 100,
    "image_url": "https://example.com/img.png"
}

### 添加商品到购物车
POST http://localhost:8080/cart
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "product_id": 1,
  "quantity": 2
}

### 查看购物车
GET http://localhost:8080/cart
Authorization: Bearer {{token}}


### 创建订单
# @name createOrder
POST http://localhost:8080/orders
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "items": [
    { "product_id": 1, "quantity": 2 }
  ]
}
###
@orderId = {{createOrder.response.body.$.data.order.id}}

### 支付订单（订单ID先用你创建返回的，别写死3）
POST http://localhost:8080/orders/{{orderId}}/pay
Authorization: Bearer {{token}}
Content-Type: application/json

### 获取当前用户所有订单
GET http://localhost:8080/orders
Authorization: Bearer {{token}}

### 查看某一个订单详情
GET http://localhost:8080/orders/{{orderId}}
Authorization: Bearer {{token}}

###
POST  http://localhost:8080/orders/{{orderId}}/pay
Authorization: Bearer {{token}}
Content-Type: application/json
